```{r}
library(bipartite)
source("crossing_minimization.R")
web <- motten1982
P <- coarse_part(web)
unlist(P)
P2 <- coarse_part(t(web[, unlist(P)]))
```

```{r, fig.width=10, fig.height=8}
source("draw_link.R")
source("plotweb_v2.R")
plotweb_v2(web, horizontal = TRUE, style = "curve", upper_color = upper_colors, link_color = "upper")
plotweb_v2(web[, unlist(P)], horizontal = TRUE, style = "curve", upper_color = upper_colors, link_color = "upper")
plotweb_v2(web[unlist(P2), unlist(P)], horizontal = TRUE, style = "curve", upper_color = upper_colors, link_color = "upper")
```

```{r}
ind <- unlist(lapply(P, function(x) !is.null(x)))
named_parts <- lapply(P[ind], function(x) colnames(web)[x])
```

```{r}
c25 <- c(
  "dodgerblue2", "#E31A1C", # red
  "green4",
  "#6A3D9A", # purple
  "#FF7F00", # orange
  "black", "gold1",
  "skyblue2", "#FB9A99", # lt pink
  "palegreen2",
  "#CAB2D6", # lt purple
  "#FDBF6F", # lt orange
  "gray70", "khaki2",
  "maroon", "orchid1", "deeppink1", "blue1", "steelblue4",
  "darkturquoise", "green1", "yellow4", "yellow3",
  "darkorange4", "brown"
)
upper_colors <- c()
for (i in seq_along(named_parts)) {
  for (name in named_parts[[i]]) {
    #print(name)
    upper_colors[name] <- c25[i]
  }
}
upper_colors
```

```{r}
start <- Sys.time()
P <- coarse_part(web)
end <- Sys.time()
end - start

system.time( { P <- coarse_part(web) } )
```

```{r}
bm <- microbenchmark(coarse_part(web), unit = "ms", times = 10000)
summary(bm)
```
