# How to Plot

```{r}
library(bipartite)
source("./sortweb2.R")
source("./plotweb_v2.R")
source("./draw_link.R")
```

## Creating a web matrix

```{r}
n_higher_species <- 7
n_lower_species <- 15
higher_species <- paste("Pollinator", 1:n_higher_species)
lower_species <- paste("Plant", 1:n_lower_species)
web <- matrix(sample(0:100, n_higher_species * n_lower_species, replace = TRUE, prob = c(50, sqrt(1/(1:100)))), 
              ncol = n_higher_species,
              nrow = n_lower_species)
colnames(web) <- higher_species
rownames(web) <- lower_species
web
```

## Plotting the old way

```{r, fig.width=10, fig.heigth=10}
source("./plotweb_v2.R")
plotweb(web, method = "cca")
plotweb(motten1982, method = "cca")
```

## Plotting the new way

```{r, fig.width=15, fig.heigth=10}
source("./plotweb_v2.R")
plotweb_v2(web, sorting = "cca")
plotweb_v2(web, sorting = "cca", srt = 90, lab_distance = 0.4)
```

```{r, fig.height = 10, fig.width = 10}
source("./plotweb_v2.R")
plotweb(motten1982)
plotweb_v2(web)
plotweb_v2(motten1982, text_size=0.9, sorting = "cca")
plotweb_v2(motten1982, text_size=1, horizontal = T, sorting = "cca", style = "curve")
```

## Changing the layout

### Switching to a horizontal plot

```{r}
plotweb_v2(motten1982, horizontal = T, text_size = 0.5)
```

## Changing the style

### Additional abundances colors

```{r}
source("./plotweb_v2.R")
u_add_abun <- sample(0:100, n_higher_species, replace = TRUE)
names(u_add_abun) <- higher_species
print(u_add_abun)
add_u_colors <- c("Pollinator 7" = "blue",
                  "Pollinator 6" = "black",
                  "Pollinator 5" = "black",
                  "Pollinator 4" = "red",
                  "Pollinator 3" = "black", 
                  "Pollinator 2" = "red",
                  "Pollinator 1" = "black")
plotweb_v2(web, horizontal = TRUE)
plotweb_v2(web, add_upper_abundances = u_add_abun, horizontal = TRUE, upper_color = "green", upper_border = "black", upper_add_color = add_u_colors, link_color = "upper")
```

```{r}

```

```{r}

```
