%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{test}


\documentclass[a4paper, 11pt]{article}
\usepackage[sc]{mathpazo}
\usepackage[utf8]{fontenc}
\usepackage{geometry}
\geometry{verbose,tmargin=3cm,bmargin=3cm,lmargin=3cm,rmargin=3cm}
\setcounter{secnumdepth}{2}
\setcounter{tocdepth}{2}
\setlength{\parskip}{\bigskipamount}
\setlength{\parindent}{0pt}
\usepackage{url}
\usepackage[unicode=true,pdfusetitle,
 bookmarks=true,bookmarksnumbered=true,bookmarksopen=true,bookmarksopenlevel=2,
 breaklinks=false,pdfborder={0 0 1},backref=true,colorlinks=false]
 {hyperref}
%\hypersetup{ pdfstartview={XYZ null null 1}}
\usepackage{breakurl}

\makeatletter
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% User specified LaTeX commands.
\renewcommand{\textfraction}{0.05}
\renewcommand{\topfraction}{0.8}
\renewcommand{\bottomfraction}{0.8}
\renewcommand{\floatpagefraction}{0.75}

\newcommand{\package}[1]{\texttt{#1}}
\newcommand{\proglang}[1]{\textsl{#1}}
\newcommand{\code}[1]{\texttt{#1}}
\newcommand{\ind}[1]{#1\index{#1}}           			   % \ind{bla} instead of bla\index{bla}
\newcommand{\indE}[1]{\emph{#1}\index{#1@\emph{#1}}}       % dito for emphasised words (e.g. English)
\newcommand{\indR}[1]{\texttt{#1}\index{#1@\texttt{#1}}}   % dito for typewriter

\renewcommand{\vec}[1]{\mathbf{#1}}                   % replaces the arrow over vectors by bold-print


\makeatother

\begin{document}
<<setup, include=FALSE, cache=FALSE>>=
library(knitr)
opts_chunk$set(fig.path='figure/twocolumn-', fig.align='center', fig.show='hold')
render_listings()
@

\title{Using bipartite to describe and plot two-mode networks}

\author{Carsten F. Dormann}


\maketitle

\begin{abstract}
This vignette introduces the bipartite package to newbees.
\end{abstract}

\tableofcontents


There are several open-source packages devoted to the analysis of networks and food webs, but only few addressing bipartite networks explicitly. Of these, \package{bipartite} provides the most extensive set of features, both for plotting, computing indices, and for null models. For the sake of completeness, here are some other \proglang{R} packages handling bipartite networks (in alphabetical order):
\begin{description}
\item[\package{AnnotationDbi}] for handling bimaps and annotation maps;
\item[\package{biGraph}]
\item[\package{econullnetr}]
\item[\package{igraph}]
\item[\package{HiveR}] for fancy ``hive'' plots;
\item[\package{networksis}]
\item[\package{sna}]
\item[\package{statnet}] a set of largely one-mode network packages;
\item[\package{tnet}]
\item[\package{WGCNA}] designed for gene assays, has a small set of indices and options overlapping with those of \package{bipartite};
\end{description}


\section{Preparing data for analysis}%------------------------------------------------
Most functions in \package{bipartite} require the same type of input structure: an \ind{adjacency matrix} of what-interacts-with-what, for short called ``web''. Raw data often start as tables of individual observations, e.g.~one column containing the name of the species in the first level, another column the name of the species in the other level with which it interacts. Occasionally a third column records the number of interactions for this pair, or a weight. Also, several networks may be included into this table, so another column would provide a web-ID (e.g.~a name of the site or the web itself). The function \indR{frame2webs} is a little convenience function to convert such tables into one or more webs. Its output is a list or an array of webs in the appropriate format for further analysis.\footnote{\indR{webs2array} can make an array of previously separate webs, padding non-overlapping species with zeros.}









We can use the \texttt{figure{*}} environment in \LaTeX{} so that
figures can span over two columns. Because the output hooks use the
\textbf{framed} package which does not work well with the \texttt{figure{*}}
environment, we can either modify the output hooks or use other packages
like \textbf{listings}. For example,

<<chunk-hook, echo=2, tidy=TRUE, tidy.opts=list(width.cutoff=30)>>=
<<setup>>
@

\begin{figure*}
<<boring-plots, fig.width=5, fig.height=5, out.width='.45\\linewidth'>>=
x=rnorm(100)
par(mar=c(4,4,.1,.1))
boxplot(x)
hist(x,main='')
@

\caption{Two plots spanning over two columns.}
\end{figure*}

The output PDF file will be like: \url{https://github.com/yihui/knitr/releases/download/doc/knitr-twocolumn.pdf}.
The Rnw source of this document is at \url{https://github.com/yihui/knitr/blob/master/inst/examples/knitr-twocolumn.Rnw}.
\end{document}
